github: upload artifacts and logs on build
Signed-off-by: Austin Seipp <aseipp@pobox.com>

diff --git a/.github/workflows/build-buck2.yml b/.github/workflows/build-buck2.yml
--- a/.github/workflows/build-buck2.yml
+++ b/.github/workflows/build-buck2.yml
@@ -15,8 +15,11 @@ jobs:
       matrix:
         include:
           - os: ubuntu-latest
+            abi: x86_64-unknown-linux-gnu
           - os: windows-latest
+            abi: x86_64-pc-windows-msvc
           - os: macos-latest
+            abi: aarch64-apple-darwin
     runs-on: ${{ matrix.os }}
     timeout-minutes: 15 # NOTE (aseipp): keep in-sync with the build.yml timeout limit
 
@@ -33,10 +36,25 @@ jobs:
           sudo apt-get update && sudo apt-get install -y mold
       - name: Install DotSlash
         uses: ./.github/actions/install-dotslash
-      - name: Add build tools to $PATH
-        run: echo "$PWD/tools/bin" >> $GITHUB_PATH
       # FIXME (aseipp): use 'buck2' out of `$PATH` after we have dotslash .exe
       # shim files for windows. until then just invoke manually
       - name: buck2 build //...
+        shell: bash
         run: |
-          dotslash ./tools/bin/buck2 build //... @mode//debug
+          mkdir -p out
+          # run the build, and if it fails, still stash the log in out, then propagate the error
+          # we use 'if' so that the error so that the script doesn't fail if the build fails
+          if ! dotslash ./tools/bin/buck2 build @mode//debug //:reapi-server --out out/reapi-server.exe; then
+            cp buck-out/v2/log/*.pb.zst out
+            exit 1
+          else
+            cp buck-out/v2/log/*.pb.zst out
+          fi
+
+      - name: "Upload artifact"
+        if: always()
+        uses: actions/upload-artifact@65462800fd760344b1a7b4382951275a0abb4808
+        with:
+          name: reapi-server-${{ matrix.abi }}
+          path: out
+          retention-days: 14
